# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58a0c5580bb5d2f5e20b6c9b1bade66105dcabd39508a2898ecdde41d81c1280cc35a10176e9345b540b8377367ea1d819c9e4936af7da2c9b3099df62ee0d8c

test:
  secret_key_base: d16a3d190e00c97766c084dece823bab8ecbc85369a52b67cbc38e4a5bfaa3d35dc56c742d3da85c36ff2eba73ff0d682a8a016b5e941f5358d5a1ab51719ad5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
